name: Deploy Inetz Lab
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Não precisamos de Checkout no Runner, pois faremos direto no Servidor
      - name: Sincronizar Código e Reiniciar Serviço
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            # 1. Garante que o diretório existe e tem as permissões corretas
            sudo mkdir -p /var/inetpub/wwwroot/lab${{ vars.ALUNO_NUM }}
            sudo chown -R ${{ vars.SSH_USER }}:${{ vars.SSH_USER }} /var/inetpub/wwwroot/lab${{ vars.ALUNO_NUM }}
            
            # 2. Entra na pasta ou clona se for a primeira vez
            cd /var/inetpub/wwwroot/lab${{ vars.ALUNO_NUM }}
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            fi

            # 3. Sincroniza o código (O volume do Docker reflete isso na hora)
            git fetch origin main
            git reset --hard origin/main

            # 4. Atualiza o serviço para garantir que o Python recarregue o código novo
            # Nota: Ele usa a imagem base definida na Stack, não buildamos nada aqui.
            docker service update --force labs_python_lab${{ vars.ALUNO_NUM }}